### ISSUE TITLE
Atma Fate Tracker

### ISSUE THREAD

**Issue by po84** [po84/ffxiv_atma_tracker#1]
- [ ] North Shroud - Archer 
- [ ] Central Shroud - Maiden 
- [ ] East Shroud - Goat 
- [ ] Eastern Thanalan - Bull
- [ ] Souther Thanalan - Scorpion
- [ ] Central Thanalan - Scales 
- [ ] Western Thanalan - Twins 
- [ ] Middle La Noscea - Ram 
- [ ] Lower La Noscea - Fish 
- [ ] Western La Noscea - Crab 
- [ ] Upper La Noscea - Water-bearer 
- [ ] Outer La Noscea - Lion
